/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uwika.view;

import com.uwika.service.KoneksiMySQL;
import java.sql.PreparedStatement;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author gunanto
 */
public class LaporanView extends javax.swing.JPanel {

    PreparedStatement preparedStatement;
    
    /**
     * Creates new form LaporanView
     */
    public LaporanView() {
        initComponents();
        
        for(int i = 1970; 2100 > i; i++)
        {
            comboBoxTahun.addItem(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboBoxBulan = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btnCetakPendudukPindahDatangMati = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtKepalaDesaSugeng = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboBoxTahun = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        calendarTanggalPertumbuhanPenduduk = new de.wannawork.jcalendar.JCalendarComboBox();
        btnCetakPertumbuhanPenduduk = new javax.swing.JButton();

        jLabel1.setText("Laporan Penduduk Pindah / Datang Dan Mati");

        comboBoxBulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Febuari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        jLabel2.setText("Bulan :");

        btnCetakPendudukPindahDatangMati.setText("Cetak");
        btnCetakPendudukPindahDatangMati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakPendudukPindahDatangMatiActionPerformed(evt);
            }
        });

        jLabel3.setText("Kepala Desa Sugeng");

        txtKepalaDesaSugeng.setText("MISMANDONO");

        jLabel4.setText("Tahun :");

        jLabel5.setText("Laporan Pertumbuhan Penduduk");

        jLabel6.setText("Tanggal");

        btnCetakPertumbuhanPenduduk.setText("Cetak");
        btnCetakPertumbuhanPenduduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakPertumbuhanPendudukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCetakPendudukPindahDatangMati)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBoxBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(65, 65, 65)))
                        .addGap(214, 214, 214)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKepalaDesaSugeng, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCetakPertumbuhanPenduduk)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboBoxTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel5)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(calendarTanggalPertumbuhanPenduduk, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtKepalaDesaSugeng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboBoxTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(btnCetakPendudukPindahDatangMati)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(calendarTanggalPertumbuhanPenduduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCetakPertumbuhanPenduduk)
                .addContainerGap(224, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCetakPendudukPindahDatangMatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakPendudukPindahDatangMatiActionPerformed
        // TODO add your handling code here:
        try{
                        JasperDesign jasperDesign = JRXmlLoader.load(LaporanView.class.getResourceAsStream("/com/uwika/laporan/laporan_penduduk_mutasi.jrxml"));
	            preparedStatement = KoneksiMySQL.getConnection().prepareStatement("select d.namaLengkap, d.nik, m.keterangan from data_penduduk d inner join mutasi m on d.nik = m.nik where MONTH(m.tanggal) =  " + (comboBoxBulan.getSelectedIndex() + 1) + " AND YEAR(m.tanggal) = " + comboBoxTahun.getSelectedItem().toString() );

	            HashMap<String,Object> param = new HashMap<String,Object>();
                    param.put("kepalaDesa", txtKepalaDesaSugeng.getText());
                    param.put("bulan", comboBoxBulan.getSelectedItem().toString().toUpperCase());
                    param.put("tahun", comboBoxTahun.getSelectedItem().toString().toUpperCase());
	            JRDesignQuery newQuery = new JRDesignQuery();
	            newQuery.setText(preparedStatement.toString().split("\\:")[1]);
	            jasperDesign.setQuery(newQuery);
	            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
	            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,param, KoneksiMySQL.getConnection());
	            JasperViewer.viewReport(jasperPrint,false);
        }catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnCetakPendudukPindahDatangMatiActionPerformed

    private void btnCetakPertumbuhanPendudukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakPertumbuhanPendudukActionPerformed
        // TODO add your handling code here:
        try{
                    JasperDesign jasperDesign = JRXmlLoader.load(LaporanView.class.getResourceAsStream("/com/uwika/laporan/laporan_pertumbuhan_penduduk.jrxml"));
	            HashMap<String,Object> param = new HashMap<String,Object>();
                    param.put("tanggal", calendarTanggalPertumbuhanPenduduk.getDate());
                    param.put("kepalaDesa", txtKepalaDesaSugeng.getText());
	            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
	            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,param, KoneksiMySQL.getConnection());
	            JasperViewer.viewReport(jasperPrint,false);
        }catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnCetakPertumbuhanPendudukActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetakPendudukPindahDatangMati;
    private javax.swing.JButton btnCetakPertumbuhanPenduduk;
    private de.wannawork.jcalendar.JCalendarComboBox calendarTanggalPertumbuhanPenduduk;
    private javax.swing.JComboBox comboBoxBulan;
    private javax.swing.JComboBox comboBoxTahun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtKepalaDesaSugeng;
    // End of variables declaration//GEN-END:variables
}
